version: "3.9"  # optional since v1.27.0
services:
  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=value
      - MONGO_DB_CONNECTION_STRING=mongodb+srv://root:DCDz5epExwpOWZDn@cluster0.gaeua2r.mongodb.net/?retryWrites=true&w=majority
      - MONGO_DB_NAME=Cluster0
      - REDIS_URI=cache:6379


  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  db:
    driver: local
  cache:
    driver: local